// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXS6GN-kBfMwuOnk-XRVFiC-1zjZney3U',
    appId: '1:967340221725:web:1e2a3a9474cc0a97b7edf4',
    messagingSenderId: '967340221725',
    projectId: 'ecommerce-c2ce8',
    authDomain: 'ecommerce-c2ce8.firebaseapp.com',
    storageBucket: 'ecommerce-c2ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHUjvN8xqZ8jkOeMn8h9b1kcjjdW_CK4w',
    appId: '1:967340221725:android:b294939db615c17eb7edf4',
    messagingSenderId: '967340221725',
    projectId: 'ecommerce-c2ce8',
    storageBucket: 'ecommerce-c2ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwea2CxCstAypFr8wHMmnI_A5D_hwInZ0',
    appId: '1:967340221725:ios:750fab6e150cc9ceb7edf4',
    messagingSenderId: '967340221725',
    projectId: 'ecommerce-c2ce8',
    storageBucket: 'ecommerce-c2ce8.appspot.com',
    androidClientId: '967340221725-0v70pv2mlibnrm07s2k6u8m53ebbq7k6.apps.googleusercontent.com',
    iosClientId: '967340221725-a9vg0107l3uu9chrvmmgdojmm2cl9tpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
